name: Job Scraper Cron

on:
  schedule:
    - cron: '*/20 * * * *' # हर 20 मिनट में अपने आप चलेगा
  workflow_dispatch: # मैन्युअल चलाने के लिए

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Scraper
      run: python scraper.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add sent_updates.txt
        git commit -m "Update sent links log" || exit 0
        git push
